### ISSUE TITLE
Cannot register an addon that is bigger than single file

### ISSUE THREAD

**Issue by karlisup** [mondeja/pytest-blender#51]
I did play a bit, but couldn't figure out a way to install an addon which consists of more than one file e.g.
```
__init__.py
other.py
blends/
  blendfile.py
```

If `.zip` provided no addon is found with error message:
`ERROR tests/test_addon_enabling.py::test_basic_addon - ValueError: Any addons found in <path here>`
If extracted each python file is interpreted as an addon (?)
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/3999661/162637197-891b12c6-cbe6-4936-98f2-94a8190e5554.png">

Thought that an opening issue could bring me some clarity.
P.S. thank you for the wonderful work developing this utility!

**Comment by mondeja** [comment]
I'll help in this possible patch if you find out a way of do the same with plain Blender because I don't have time to dig into this and no motivation for it. The installation of addons [is currently done using `bpy.ops.preferences.addon_install` and `addon_utils.enable`](https://github.com/mondeja/pytest-blender/blob/064d5b43d8a07787718f53afbe11726176dbf85b/pytest_blender/run_pytest.py#L239-L246).

**Comment by karlisup** [comment]
I did manage to install a _.zip_ and run few tests. Created PR indicating changes that allowed me to importa zipped addon. Before opening PR did run addon tests to make sure that they do not fail. I hope that you will find this useful.

**Comment by mondeja** [comment]
Would you mind to add a test?

**Comment by karlisup** [comment]
Hi @mondeja,
Unfortunately, I do not have a vast experience in testing if any.  Currently, addon installation is done using `conftest.py` for every test contained in the folder. What would be suggested folder structure where to put tests cases that check validity of installation of an addon (zip, python file, python file with version extension)?

**Comment by mondeja** [comment]
This feature has been added [v2.0.0](https://github.com/mondeja/pytest-blender/releases/tag/v2.0.0). Just zip your addon and place it in the root of the directory passed to [`install_addons_from_dir`](https://github.com/mondeja/pytest-blender#install_addons_from_dir) fixture.

Thanks for your report and attempts to fix it 👍🏼
