### ISSUE TITLE
Expose addon zippification function defined in *conftest.py*?

### ISSUE THREAD

**Issue by mondeja** [mondeja/pytest-blender#57]
If I'm developing an addon I don't want to write a custom function to convert into ZIP every time that I want to test it. Maybe allow to pass a directory to `install_addons_from_dir` converting it to zip before installing? This would be great!

**Comment by karlisup** [comment]
I do think that this would be a great addition to the plugin. We currently, use our custom built-in script that is executed before testing. It is slightly modified with features we require (clearing addon from unnecessary files/folders and postfixing addon with version). I hope you find the script useful.
[package_addon.py.zip](https://github.com/mondeja/pytest-blender/files/8685191/package_addon.py.zip)

**Comment by mondeja** [comment]
Hi @karlisup. This has been added in v3.0.0. You can add now a package in the root of the directory passed to `install_addons_from_dir` and will be automatically zipped and installed in Blender. But you probably want to use the new [`blender-addons-dirs`](https://github.com/mondeja/pytest-blender#blender-addons-dirs) configuration option to avoid the need of a *conftest.py*. You've a complete migration guide in the [release changelog entry](https://github.com/mondeja/pytest-blender/releases/tag/v3.0.0).

Thanks for your report and don't hesistate to ask anything or send more feedback. Cheers!
