### ISSUE TITLE
'_bpy.ops' has no attribute 'render'

### ISSUE THREAD

**Issue by karlisup** [mondeja/pytest-blender#64]
I am trying to make a render, change some parameters and do another. Doing it via CLI - creating two blend files and then executing them seems like a bit too much 🤷 . Is there a way to execute the render operator under `_bpy.context`?
```
filename = 'stars_before.jpg'

    def _render_image(filename):
        _bpy.context.scene.render.image_settings.file_format='JPEG'
        _bpy.context.scene.render.filepath =  os.path.join(images_dir, filename)
>       _bpy.ops.render.render(use_viewport = True)
E       AttributeError: module '_bpy.ops' has no attribute 'render'

tests/unit-tests/test_stars_texture.py:31: AttributeError
```

Could you explain where `_bpy` come from and what information is accessible and when? Another day I noticed when writing a test and trying to access an operator that I could access through Blender console, I couldn't access it through `_bpy.ops` which was quite confusing.

**Comment by mondeja** [comment]
Nope, this is the bug tracker for pytest-blender.

**Comment by karlisup** [comment]
My bad. I thought that it is part of and developed for _pytest-blender_ package.
