### ISSUE TITLE
When fetching blender version on Windows gets error msg

### ISSUE THREAD

**Issue by karlisup** [mondeja/pytest-blender#67]
This is the error message I am getting
```
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/pytest_blender/run_pytest.py", line 86, in get_blender_version
    return version_stdout.decode("utf-8").splitlines()[0].split(" ")[1]
IndexError: list index out of range
```

I understood from [get_blender_version](https://github.com/mondeja/pytest-blender/blob/310875b8c529a8ed3ef4840c4ef5505c7fa77524/pytest_blender/utils.py#L50) function then version gets retrieved by executing executable + ` --version` in CLI which doesn't work on the Windows OS.

**Comment by mondeja** [comment]
Could you share the output provided by Blender when executing `blender --version` on Windows?

**Comment by karlisup** [comment]
- [X] Blender is installed.
- [X] There is no specific PATH in the System Environment Variables, but I've located the blender executable which should, do, right?

It seems that the last error was caused when I was using `blender-launcher.exe` instead of `blender.exe`
Now `"/mnt/c/Program Files/Blender Foundation/Blender 3.0/blender.exe" --version` returns me this:
```
Blender 3.0.1
        build date: 2022-01-26
        build time: 01:46:57
        build commit date: 2022-01-25
        build commit time: 17:19
        build hash: dc2d18018171
        build platform: Windows
        build type: release
[..]
```

Thank you for your time and prompt answer!
