### ISSUE TITLE
blender_python interpreter location returned None on Windows 10

### ISSUE THREAD

**Issue by karlisup** [mondeja/pytest-blender#68]
Hi again 👋,
When I run a command:
`pytest-blender --blender-executable "/mnt/c/Program Files/Blender Foundation/Blender 3.0/blender.exe"`
It returns `None`. Any idea why?

Didn't want to follow up with a different question on the same issue so created a new one.

**Comment by mondeja** [comment]
It's probably a bug, I'll fix it ASAP.

**Comment by mondeja** [comment]
Hmm, that's weird 🤔 Would you mind to execute the next commands and paste the results here?

- `path/to/blender.exe --version`
- `path/to/blender.exe -b --python-expr "import bpy;print(bpy.app.binary_path_python)"`
- `path/to/blender.exe -b --python-expr "import sys;print(sys.executable)"`

**Comment by mondeja** [comment]
Maybe you want to try v3.0.3

**Comment by mondeja** [comment]
Maybe you want to try v3.0.3

**Comment by karlisup** [comment]
Sorry wasn't at the PC all this day.
Eureka! v3.0.3 returns python executable! Thanks!
