### ISSUE TITLE
pytest-cov won't work with blender-addons-dirs

### ISSUE THREAD

**Issue by matyalatte** [mondeja/pytest-blender#75]
Hi, I installed Blender 3.0.1 on Windows 10 with blender-downloader.
And used `blender-addons-dirs` option in `setup.cfg`.
Then, pytest-cov will report all `def` and `class` lines as missing lines.

If I remove the option from setup.cfg and add the addon path to script path in user preferences, pytest-cov will work perfectly.

So, I need to run this script before running pytest for Github Actions.
```
bpy.context.preferences.filepaths.script_directory = os.getcwd()
bpy.ops.wm.save_userpref()
```

I uploaded resource files to [my addon repo](https://github.com/matyalatte/Blender-Uasset-Addon/tree/dev) as dev branch.
The testing workflow is [test.yml](https://github.com/matyalatte/Blender-Uasset-Addon/blob/dev/.github/workflows/test.yml).
If I remove the line 77 from `test.yml` and add `blender-addons-dirs = addons` to `setup.cfg`, pytest-cov will report the wrong coverage.

**Comment by mondeja** [comment]
Would you mind to submit a minimal reproducible example?

**Comment by matyalatte** [comment]
Here it is.
[pytest-cov-test.zip](https://github.com/mondeja/pytest-blender/files/9065783/pytest-cov-test.zip)

\_\_init__.py will import a module.
and the module will import another module pytest will test.

I got this when run
`pytest tests\ -svv --cov --blender-executable "%BLENDER_EXE%" --cov-report html `
![result](https://user-images.githubusercontent.com/69258547/177825719-d9819dd3-52b5-497c-bc22-3d809347a78e.png)

But remove import sentences from \_\_init__.py will fix the issue.

**Comment by matyalatte** [comment]
I found this.
https://github.com/pytest-dev/pytest-cov/issues/455

Blender will import the modules before running pytest-cov?

**Comment by mondeja** [comment]
Thanks, I can reproduce it in Linux as well. It seems that is what you've pointed because addons enabling is done using [`addon_utils` module which imports modules](https://github.com/johnathaningle/blender-python/blob/46f46fc836658cf6a79152decc515d4d3f284d85/addon_utils.py#L351) to get the minimum Blender version required for addons.

I suspect that should be fixable enabling the addons before running blender, but is not a straightforward fix.

**Comment by mondeja** [comment]
OK, I've simplifyed the example and executed with `--cov=~/.config/blender/3.0/scripts/addons/addon` and it works well, as expected: [pytest-cov-test.zip](https://github.com/mondeja/pytest-blender/files/9066459/pytest-cov-test.zip)

The full command has been:

```
pytest tests -svv --blender-executable blender-3.0.1-linux-x64/blender --cov ~/.config/blender/3.0/scripts/addons/addon
```

Note that you must cover the addon that is copied into `scripts/addons`. That's the way how pytest-blender works with `blender-addons-dirs`, you must know that enabling your addon means that Blender copies it into his directory of scripts, not in your source directory. We can't do anything to control at pytest-blender's level as coverage is an external tool.

Other problem that I've seen is that you're not exposing a `register` function, so Blender does not consider it a valid addon I guess, I can see in the traceback:

```
Exception in module register(): ~/.config/blender/3.0/scripts/addons/addon/__init__.py
Traceback (most recent call last):
  File "/.../pytest-cov-test-3/blender-3.0.1-linux-x64/3.0/scripts/modules/addon_utils.py", line 387, in enable
    mod.register()
AttributeError: module 'addon' has no attribute 'register'
```

So please, share a valid minimal addon if you still having problems like that, but IHMO as far as I can see it is everything OK.

**Comment by matyalatte** [comment]
> Other problem that I've seen is that you're not exposing a register function

I just removed it because it was not related to the issue. So, everything is OK.

> OK, I've simplifyed the example and executed with --cov=~/.config/blender/3.0/scripts/addons/addon and it works well

Yeah, `--cov=path_to_copied_addon` worked for me.
But it's a little hacky because we need to get the path.

Thanks for the investigation, but I'll use my first method that registers current dir to user preferences for now.


Today, I searched for better solutions and found this.
https://blenderartists.org/t/adding-more-python-module-search-paths-to-blender/1301763
We can add startup script to register the addon paths.

And found this.
https://docs.blender.org/manual/ja/3.0/advanced/command_line/arguments.html
There is `--python-use-system-env` to register paths to blender.exe.

As a test, I tried this batch file with `./addons/test_addon`.
```
set PYTHONPATH=%~dp0addons
%BLENDER_EXE% --python-use-system-env
```
Then, this script worked in blender
```
import test_addon
test_addon.register()
```

So, there might be a way to use `--cov=addons` not `--cov=path_to_copied_one`.

I hope you will find the way.

**Comment by matyalatte** [comment]
Another test.
Blender can read `./addons` with this python script.
```
import sys, os
import subprocess

blender_exe='D:\\Blender\\3.0\\blender.exe'
pythonpath = f'{os.getcwd()}\\addons'
os.environ['PYTHONPATH'] = pythonpath
subprocess.run(f'{blender_exe} --python-use-system-env')
```

**Comment by mondeja** [comment]
See `blender.exe --help`, you can also `BLENDER_USER_SCRIPTS` environment variable pointing to your addons directory, I suppose that would also work with `--cov=addons` without using `blender-addons-dirs` at all as blender would detect it as an installed addon, though in that case you can't call others addons from it.

I'm pretty sure that there are many ways to workaround this limitation and it will very much depend on how you are using the plugin. If you find an optimal solution don't hesitate to open a PR to document it. I'm going to leave this PR open until some notes about the usage of code coverage tools are added.

**Comment by matyalatte** [comment]
We can't put multiple paths to `BLENDER_USER_SCRIPTS`.
So, it's uncompatible with `blender-addons-dirs`.

I want to add paths to PYTHONPATH like this.
https://github.com/matyalatte/pytest-blender/commit/cdca795ae932d84dc32955e95a6b35f29880337d

It can get perfect covertages with `blender-addons-dirs=addons` and `--cov=addons` in my environment.

It passed your CI workflow, but I didn't care about other options.
It may have some problems.
(maybe blender-addons-cleaning won't work?)
So, I don't know if I should send PR or not.

**Comment by mondeja** [comment]
I prefer to maintain the environment and passed blender options as is, why not using `PYTHONPATH` and `--python-use-system-env` directly in your tests?

**Comment by matyalatte** [comment]
Oh, I missed we can put blender options as pytest arguments.

But I want to use setup.cfg to specify the module paths.
It'll just add specified paths to Blender's sys.path.

like this
https://github.com/matyalatte/pytest-blender/commit/c598f798561744edde9b3135526b68fc9e5b1c19

**Comment by mondeja** [comment]
> Oh, I missed we can put blender options as pytest arguments.

See [Arguments propagation](https://github.com/mondeja/pytest-blender#arguments-propagation).

> like this
> https://github.com/matyalatte/pytest-blender/commit/c598f798561744edde9b3135526b68fc9e5b1c19

No way, that would override [pytest's `--pythonpath`](https://docs.pytest.org/en/7.1.x/reference/reference.html#confval-pythonpath), have you tried with that option? You can put it in `setup.cfg`.

**Comment by matyalatte** [comment]
> No way, that would override [pytest's --pythonpath](https://docs.pytest.org/en/7.1.x/reference/reference.html#confval-pythonpath), have you tried with that option?

That's it!
I finally got the perfect solution.
Use `pythonpath` instead of `blender-addons-dirs`.
I really appreciate it.
You can close this issue.
